### ISSUE TITLE
建议加上token数

### ISSUE THREAD

**Issue by mmeiwenlong** [Merrickk/BncrFiles#2]
没这个好像不好对接

**Comment by Merrickk** [comment]
加上token数是什么意思，和对接有啥关系

**Comment by mmeiwenlong** [comment]
> 加上token数是什么意思，和对接有啥关系

提示服务器异常怎么回事？我这ip对接应该没有问题，对接奥特曼的微信客服很稳，对接这个就接不上了，

**Comment by mmeiwenlong** [comment]
> 加上token数是什么意思，和对接有啥关系
![QQ截图20240304220631](https://github.com/Merrickk/Bncr_plugins/assets/44661424/f923fe36-f9cb-4f61-99ef-5bf1fc7edc99)
参数是在这一页获取的么？
