### ISSUE TITLE
回调URL填“无界地址/api/bot/wxWork”要加KF

### ISSUE THREAD

**Issue by zhao316678171** [Merrickk/BncrFiles#4]
回调URL填“无界地址/api/bot/wxWork”应该是“无界地址/api/bot/wxWorkKF”，不然就联不通，加了瞬间好了

**Comment by zhao316678171** [comment]
按教程弄好了，但是还是不会用，谁知道怎么玩或者有没有电报群或者交流群，可以发下一起研究

**Comment by Merrickk** [comment]
> 回调URL填“无界地址/api/bot/wxWork”应该是“无界地址/api/bot/wxWorkKF”，不然就联不通，加了瞬间好了

我改一下，谢谢反馈

**Comment by Merrickk** [comment]
> 按教程弄好了，但是还是不会用，谁知道怎么玩或者有没有电报群或者交流群，可以发下一起研究

有问题可以到我群里咨询，https://t.me/+V2q6Okh6GupiNGI1

**Comment by Merrickk** [comment]
已修改教程
