### ISSUE TITLE
微信公众号适配器发送图片会失败

### ISSUE THREAD

**Issue by doyoman** [Merrickk/BncrFiles#5]
![image](https://github.com/Merrickk/Bncr_plugins/assets/63859866/25b81205-156c-4d94-848e-5718b67d0c46)
如图，发送pro的二维码的时候，会报错，这个报错不是白名单的问题

**Comment by Merrickk** [comment]
请联系插件作者适配本适配器，或换用D佬的登录.js

**Comment by doyoman** [comment]
用D佬的也报这个错
![image](https://github.com/Merrickk/Bncr_plugins/assets/63859866/35168276-c7cb-4dbf-a759-cae926e53194)

**Comment by M-a-s-a-t-o** [comment]
跟登录.js插件没关系，npm i form-data升级一下form-data库就行了
